---
# This role installs httpd

- name: Install http
  apt:
    name:
      - httpd
      - php
      - php-mysql
      - git
    update_cache: yes
    state: present

- name: Configure SELinux to allow httpd to connect to remote database
  seboolean:
    name: httpd_can_network_connect_db
    state: yes
    persistent: yes
  when: sestatus.rc != 0

- name: http service state
  service:
    name: httpd
    state: started
    enabled: yes
