---
# This role contains common plays that will run on all nodes.

- name: Install python bindings for SE Linux
  apt:  
    state: present 
    update_cache: yes
    name:
      - python-selinux
      - python-semanage

- name: install some useful nagios plugins
  apt: 
    state: present
    name:
      - nagios-nrpe-plugin
      - nagios-plugins
      # - nagios-plugins-swap
      # - nagios-plugins-users
      # - nagios-plugins-procs
      # - nagios-plugins-load
      # - nagios-plugins-disk

- name: Install ntp
  apt: name=ntp state=present
  tags: ntp

- name: Configure ntp file
  template: src=ntp.conf.j2 dest=/etc/ntp.conf
  tags: ntp
  notify: restart ntp

- name: Start the ntp service
  service: name=ntpd state=started enabled=yes
  tags: ntp

# work around RHEL 7, for now
# - name: insert iptables template
#   template: src=iptables.j2 dest=/etc/sysconfig/iptables
#   when: ansible_distribution_major_version != '7'
#   notify: restart iptables

- name: test to see if selinux is running
  command: getenforce
  register: sestatus
  changed_when: false
